# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        run: curl -fsSL https://deno.land/install.sh | sh

      - name: Build for Windows
        run: ~/.deno/bin/deno run windows

      - name: Upload build as artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: "*.exe"
          path: '.'